feat(api): Added http handling and Axious
LePashtet/newsletter_mvp pull request #5
Opened 2024-08-07 16:24 UTC by moxort

Added axious as a dependency,
created api folder, 
added TODOs to fix in future

2024-08-08 15:48 UTC, LePashtet commented on frontend/src/api/AxiosInstance.ts
> +    baseURL: 'https://api.example.com',
move baseURL to env variables

2024-08-08 15:51 UTC, LePashtet commented on frontend/src/api/AxiosInstance.ts
> +const axiosInstance = axios.create({
axiosInstance too long, usually just API is used

2024-08-08 15:53 UTC, LePashtet requested changes

2024-08-08 15:53 UTC, LePashtet commented on frontend/src/api/AxiosInstance.ts
> +    timeout: 1000,
1 sec is too short, let's make it harder to drop and increase up to 5

2024-08-08 15:53 UTC, LePashtet commented on frontend/src/api/UserApi.ts
user just enough it in api folder, right?)

2024-08-08 15:54 UTC, LePashtet commented
4 commetns added

2024-08-08 18:59 UTC, moxort commented on frontend/src/api/UserApi.ts
true

2024-08-09 15:26 UTC, LePashtet approved these changes

2024-08-09 15:26 UTC, LePashtet commented
Well Done!

2024-08-09 15:26 UTC, merged